const nodes = [
  {id:'root', type:'root', branch:'root', x:1500, y:1080, icon:'photo', title:'Toundé ALOGBO', subtitle:'Validation · QA · Data clinique · HealthTech', kicker:'IDENTITÉ PROFESSIONNELLE', lead:'Un profil hybride construit à l’intersection des sciences du vivant, des données cliniques, du développement logiciel et de la validation.', chips:['Master 2 GPhy','Poitiers','Validation EDC','Data clinique'], bullets:['Comprendre un besoin et le traduire en vérifications exploitables.','Documenter les constats avec traçabilité et reproductibilité.','Relier les enjeux métier, qualité, données et réalités techniques.'], evidence:'Ma signature professionnelle : comprendre le besoin, vérifier de façon structurée et contribuer à la confiance accordée à une solution.'},

  {id:'validation', type:'branch', branch:'validation', x:1950, y:760, icon:'V', title:'Validation & Qualité', subtitle:'Le cœur de métier', kicker:'CŒUR DE MÉTIER', lead:'Vérifier qu’un logiciel répond au besoin attendu, documenter les écarts et contribuer à la maîtrise du risque.', chips:['Squash TM','Non-régression','API','Migration','Traçabilité'], bullets:['Tests fonctionnels manuels, acceptation, non-régression et sorties de version.','Tests API, multi-base et vérifications de migration selon le contexte.','Analyse d’anomalies, documentation et suivi des écarts.'], evidence:'La qualité ne se limite pas à exécuter un scénario : elle consiste aussi à comprendre pourquoi on vérifie et à rendre le résultat démontrable.'},
  {id:'ennov-alt', type:'node', branch:'validation', x:2240, y:520, icon:'E', title:'Alternance Ennov', subtitle:'2025–2026 · EDC', kicker:'EXPÉRIENCE STRUCTURANTE', lead:'Assistant ingénieur validation sur un produit EDC utilisé dans l’environnement des essais cliniques.', chips:['EDC','ePRO','Squash TM','Agile Scrum'], bullets:['Analyse de spécifications fonctionnelles.','Rédaction et maintenance de cas de test dans Squash TM.','Campagnes de validation et non-régression.','Tests d’acceptation, API, migration, multi-base et release.','Remontée, documentation et suivi d’anomalies.'], evidence:'Cette alternance renforce ma capacité à transformer un besoin en vérification structurée et à communiquer clairement les écarts.'},
  {id:'ennov-stage', type:'node', branch:'validation', x:2290, y:760, icon:'S', title:'Stage Ennov', subtitle:'Juin–août 2025', kicker:'PREMIÈRE IMMERSION EN VALIDATION', lead:'Découverte du métier d’ingénieur validation dans un environnement logiciel exigeant.', chips:['Audit fonctionnel','Feature mapping','eDoc','eProcess'], bullets:['Prise en main de Squash TM et des outils de validation.','Contribution à un audit fonctionnel des éléments de test.','Feature mapping autour d’eDoc et d’eProcess.','Sensibilisation à la documentation réglementaire et aux processus qualité.'], evidence:'Cette immersion a confirmé mon intérêt pour la validation logicielle et préparé la poursuite en alternance.'},
  {id:'refs', type:'micro', branch:'validation', x:2070, y:995, icon:'R', title:'Référentiels', subtitle:'GAMP 5 · GxP · ALCOA+', kicker:'REPÈRES QUALITÉ', lead:'Repères et sensibilisation : GAMP 5, GxP, ALCOA+, 21 CFR Part 11, ICH-GCP et RGPD.', chips:['GAMP 5','GxP','ALCOA+','21 CFR Part 11','ICH-GCP','RGPD'], bullets:['Connaissances en approfondissement selon les responsabilités confiées.','Aucune expertise d’audit réglementaire en autonomie n’est revendiquée.'], evidence:'Le portfolio distingue les notions connues des responsabilités effectivement exercées.'},
  {id:'istqb', type:'micro', branch:'validation', x:2335, y:1010, icon:'I', title:'ISTQB CTFL', subtitle:'En préparation', kicker:'CERTIFICATION', lead:'Objectif : consolider les fondamentaux du test logiciel avec l’ISTQB Foundation Level.', chips:['Fondamentaux du test','Préparation 2026'], bullets:['Certification non obtenue à la date du portfolio.','Approche fondée sur l’apprentissage et la preuve de travail.'], evidence:'Une certification n’est présentée comme acquise qu’après son obtention effective.'},

  {id:'clinical', type:'branch', branch:'clinical', x:1025, y:760, icon:'D', title:'Data clinique', subtitle:'Qualité des données', kicker:'RECHERCHE CLINIQUE', lead:'Faire le lien entre les usages cliniques, la qualité de la collecte et la fiabilité des informations produites.', chips:['EDC','eCRF','REDCap','Ennov Clinical','Queries'], bullets:['Compréhension générale du cycle de vie des données d’étude clinique.','Conception, paramétrage et validation d’eCRF.','Contrôles de cohérence, qualité et complétude.'], evidence:'Ma valeur ajoutée : comprendre à la fois la finalité d’une donnée clinique et le logiciel qui permet de la recueillir ou de la contrôler.'},
  {id:'chu', type:'node', branch:'clinical', x:715, y:555, icon:'CHU', title:'CHU de Poitiers', subtitle:'Stage · Mai–juil. 2023', kicker:'DATA MANAGEMENT CLINIQUE', lead:'Première immersion professionnelle dans le data management clinique au sein de la DRI du CHU de Poitiers.', chips:['eCRF','REDCap','Ennov Clinical','QC'], bullets:['Sensibilisation aux protocoles d’étude et à l’organisation de la recherche hospitalière.','Design, paramétrage et validation d’eCRF.','Contrôles qualité et cohérence des données.','Archivage et réunions de suivi.'], evidence:'Cette expérience clinique constitue aujourd’hui un atout direct pour comprendre la finalité métier des logiciels EDC que je contribue à valider.'},
  {id:'clinical-concepts', type:'micro', branch:'clinical', x:680, y:815, icon:'C', title:'Concepts cliniques', subtitle:'EDC · eCRF · ePRO · CTMS', kicker:'VOCABULAIRE MÉTIER', lead:'EDC, eCRF, ePRO, CTMS, RTSM/randomisation, gestion de requêtes, export, intégrité des données, confidentialité et traçabilité.', chips:['EDC','eCRF','ePRO','CTMS','RTSM'], bullets:['Compréhension fonctionnelle et métier.','Usage selon les environnements de stage et de validation.'], evidence:'Les notions sont présentées au niveau réellement pratiqué ou étudié.'},

  {id:'science', type:'branch', branch:'science', x:1020, y:1385, icon:'S', title:'Sciences du vivant', subtitle:'Les racines scientifiques', kicker:'FONDATIONS', lead:'Comprendre le vivant avant de structurer les données et de vérifier les outils numériques utilisés en santé.', chips:['Biologie','Physiologie','Bio-informatique','Pharmacologie'], bullets:['Licence Biologie & Physiologie Animales — Université de Lomé.','Licence Génie bio-informatique — Université de Poitiers.','Master Ingénierie de la santé — parcours GPhy.'], evidence:'Le fil conducteur : comprendre les mécanismes du vivant, structurer l’information et garantir la qualité des outils numériques utilisés en santé.'},
  {id:'lome', type:'node', branch:'science', x:695, y:1515, icon:'2018', title:'Université de Lomé', subtitle:'2018–2022', kicker:'LICENCE', lead:'Licence en biologie et physiologie animales, obtenue avec la mention Assez bien.', chips:['Biologie cellulaire','Physiologie','Biochimie'], bullets:['Fondations en sciences du vivant.','Approche scientifique et raisonnement expérimental.'], evidence:'Une base scientifique qui nourrit aujourd’hui la compréhension des contextes de santé.'},
  {id:'bioinfo', type:'node', branch:'science', x:980, y:1685, icon:'2022', title:'Génie bio-informatique', subtitle:'Poitiers · 2022–2024', kicker:'LICENCE', lead:'Articulation entre biologie, programmation, systèmes informatiques et méthodes appliquées aux sciences de la vie.', chips:['Algorithmique','Systèmes','Données','Bio-informatique'], bullets:['Programmation et algorithmique.','Systèmes d’exploitation et réseaux.','Manipulation et analyse d’informations biologiques et biomédicales.'], evidence:'Cette étape a créé le pont entre les sciences du vivant et la construction logicielle.'},
  {id:'master', type:'node', branch:'science', x:1275, y:1630, icon:'M2', title:'Master Ingénierie Santé', subtitle:'GPhy · 2024–2026', kicker:'MASTER 2', lead:'Master Ingénierie de la santé, parcours Génie physiologique, biotechnologique et informatique (GPhy).', chips:['GPhy','Essais cliniques','Qualité','Validation'], bullets:['Physiologie, pharmacologie et environnement des essais cliniques.','Gestion de projet, développement de solutions numériques et validation logicielle.','Alternance professionnelle centrée sur la validation d’un produit EDC.'], evidence:'Soutenance prévue le 24 septembre 2026.'},

  {id:'dev', type:'branch', branch:'dev', x:1975, y:1385, icon:'</>', title:'Développement logiciel', subtitle:'Comprendre ce que l’on teste', kicker:'SOCLE TECHNIQUE', lead:'Le développement m’aide à mieux comprendre la construction d’un logiciel et à dialoguer avec les équipes techniques.', chips:['Python','PHP','Symfony','JavaScript','SQL'], bullets:['Applications pédagogiques et modules métiers.','Spécifications techniques et fonctionnelles.','Tests fonctionnels et documentation.'], evidence:'Une meilleure compréhension de la construction d’un logiciel permet de concevoir des tests plus pertinents.'},
  {id:'python-stage', type:'node', branch:'dev', x:2305, y:1525, icon:'Py', title:'Stage Python', subtitle:'Mai–juil. 2024', kicker:'DÉVELOPPEMENT & TEST', lead:'Évolution d’une application pédagogique illustrant des mécanismes de systèmes d’exploitation et réseaux.', chips:['Python','Tkinter','GitHub','Trello'], bullets:['Mise à jour du cahier des charges.','Spécifications techniques et fonctionnelles.','Implémentation d’un algorithme d’ordonnancement.','Tests fonctionnels et documentation.'], evidence:'Cette expérience a renforcé mon intérêt pour la qualité dès la conception.'},
  {id:'holid', type:'node', branch:'dev', x:2240, y:1760, icon:'H', title:'Holi-D / AWA Solution', subtitle:'2025–2026', kicker:'DÉVELOPPEMENT · VALIDATION · CLIENT', lead:'Contribution à un module de planning d’activités et d’animateurs dans un environnement Symfony.', chips:['Symfony','PHP','FullCalendar','CRUD'], bullets:['Clarification des besoins fonctionnels.','Intégration d’un module de planning.','Scénarios de test et documentation de validation.','Documentation technique, fonctionnelle et utilisateur.'], evidence:'Un besoin exprimé en langage métier doit être reformulé, priorisé et transformé en comportements testables.'},
  {id:'db', type:'micro', branch:'dev', x:1940, y:1700, icon:'DB', title:'Données & bases', subtitle:'SQL · MySQL · SQL Server · Oracle', kicker:'BASES DE DONNÉES', lead:'Requêtes, vérifications, compréhension de schémas et contrôles multi-environnements.', chips:['SQL','MySQL','SQL Server','Oracle','DBeaver'], bullets:['Utilisation dans les projets et les activités de vérification.','Approfondissement continu sur SQL avancé.'], evidence:'Un socle technique mobilisé selon le contexte et le niveau de pratique réel.'},

  {id:'ai', type:'branch', branch:'ai', x:1500, y:590, icon:'AI', title:'IA & Produits personnels', subtitle:'Construire et vérifier', kicker:'INNOVATION RESPONSABLE', lead:'Explorer comment des assistants et outils numériques peuvent agir dans un processus maîtrisé, avec vérification et gouvernance.', chips:['Agents IA','GitHub','CI/CD','GED','HealthTech'], bullets:['ALOGBO CORE : assistant professionnel en développement.','ATAC Kanban : plateforme opérationnelle en consolidation.','Plateforme e-santé : prototype multi-organisation.'], evidence:'Fil rouge : bâtir des systèmes dont les comportements sont vérifiables, traçables et maîtrisés.'},
  {id:'core', type:'node', branch:'ai', x:1430, y:305, icon:'A', title:'ALOGBO CORE', subtitle:'En développement', kicker:'PROJET PERSONNEL · IA', lead:'Exploration d’un assistant professionnel capable de comprendre une demande, d’agir et de vérifier ses résultats.', chips:['Python','CLI','API','GitHub','Gouvernance'], bullets:['Analyse de besoins et user stories.','Exploration de code et génération assistée.','Contrôles, documentation et traçabilité.','Réflexion sur permissions et limites d’autonomie.'], evidence:'L’IA est envisagée comme un outil d’assistance, jamais comme une preuve de conformité ou un substitut au jugement professionnel.'},
  {id:'kanban', type:'node', branch:'ai', x:1705, y:300, icon:'K', title:'ATAC Kanban', subtitle:'Opérationnel · consolidation', kicker:'PROJET PERSONNEL', lead:'Plateforme de gestion de projet orientée tâches, GED, suivi de tests, reporting et consolidation technique.', chips:['Kanban','GED','KPI','Import/Export','CI'], bullets:['Gestion de tâches et flux de travail.','Gestion électronique de documents.','Scénarios de test, reporting et indicateurs.','Migrations, base de données et préparation au déploiement.'], evidence:'Le projet illustre l’écart entre un prototype fonctionnel et une solution réellement prête à être industrialisée.'},
  {id:'health', type:'node', branch:'ai', x:1895, y:430, icon:'+', title:'Plateforme e-santé', subtitle:'Prototype V1', kicker:'DIGITALISATION SANTÉ', lead:'Prototype multi-organisation visant à structurer les services, documents et processus métiers d’établissements de santé.', chips:['Multi-organisation','GED','Rôles','Traçabilité'], bullets:['Gestion de centres, services, rôles et périmètres.','Formulaires, registres, procédures et protocoles.','Réflexion sur séparation des données, sécurité et traçabilité.'], evidence:'Prototype : aucune utilisation hospitalière en production, conformité réglementaire acquise ou certification d’hébergement n’est revendiquée.'},

  {id:'human', type:'branch', branch:'human', x:1500, y:1700, icon:'H', title:'Expériences humaines', subtitle:'L’humain derrière les systèmes', kicker:'RÉALITÉ DU TERRAIN', lead:'Des expériences qui ont consolidé mes réflexes de service, de coopération, de confidentialité et de gestion des situations exigeantes.', chips:['Service','Coopération','Résilience','Pédagogie'], bullets:['Maison Cousin Traiteur : organisation, service, adaptation et travail sous pression.','UNAPEI 86 / MAS : accompagnement humain, hygiène, vigilance et responsabilité.','Crous / Rectorat : multitâche, qualité et respect des règles.','Engagements : écoute, pédagogie et transmission.'], evidence:'Ces expériences n’effacent pas les compétences techniques : elles expliquent une partie de ma posture professionnelle — sérieux, patience, résilience et sens du travail bien fait.'},
  {id:'cousin', type:'micro', branch:'human', x:1450, y:1955, icon:'M', title:'Maison Cousin', subtitle:'Événementiel', kicker:'EXPÉRIENCE TERRAIN', lead:'Restauration événementielle : rythme, détail, coordination, service et adaptation.', chips:['Organisation','Service','Stress'], bullets:['Ponctualité et sens du détail.','Coopération dans des environnements exigeants.'], evidence:'Le terrain apprend à tenir la qualité même quand le rythme monte.'},
  {id:'unapei', type:'micro', branch:'human', x:1680, y:1940, icon:'U', title:'UNAPEI 86', subtitle:'Médico-social', kicker:'EXPÉRIENCE HUMAINE', lead:'Expérience dans un environnement accompagnant des personnes en situation de handicap.', chips:['Empathie','Vigilance','Confidentialité'], bullets:['Respect des consignes et de l’hygiène.','Adaptation et coopération avec des professionnels complémentaires.'], evidence:'Une expérience qui renforce la responsabilité et l’attention portée à l’humain.'},
  {id:'teaching', type:'micro', branch:'human', x:1900, y:1885, icon:'T', title:'Transmission', subtitle:'Associatif · soutien scolaire', kicker:'ENGAGEMENT', lead:'Écoute, pédagogie et capacité à expliquer simplement une information.', chips:['Pédagogie','Collectif','Écoute'], bullets:['Participation à la vie associative étudiante.','Expériences de soutien scolaire scientifique.'], evidence:'Transmettre oblige à clarifier sa pensée — une compétence utile en validation comme en collaboration.'},

  {id:'skills', type:'branch', branch:'root', x:1500, y:1190, icon:'✦', title:'Skill Galaxy', subtitle:'Compétences en constellation', kicker:'CARTOGRAPHIE DES COMPÉTENCES', lead:'Une lecture par domaines, outils et niveau d’usage réel.', chips:['Tests & QA','Data clinique','Développement','Bases','Méthodes','Référentiels','IA'], bullets:['Tests & qualité : Squash TM, SoapUI, Swagger, Selenium IDE, GitHub Actions.','Data clinique : Ennov Clinical, REDCap, Viedoc, EDC, eCRF, ePRO.','Développement : Python, PHP, JavaScript, Symfony, HTML/CSS.','Bases : SQL, MySQL, SQL Server, Oracle, DBeaver.','Méthodes : Agile Scrum, Kanban, cycle en V, Git.'], evidence:'Le niveau d’expertise n’est jamais gonflé : les outils sont présentés selon leur contexte d’usage réel.'},
  {id:'timeline', type:'branch', branch:'future', x:2600, y:1240, icon:'→', title:'Trajectoire 2018 → 2031', subtitle:'Progression & projection', kicker:'FEUILLE DE ROUTE', lead:'Une progression fondée sur l’expérience terrain, l’approfondissement méthodologique et la prise progressive de responsabilités.', chips:['2018','2023','2025','2026','2031'], bullets:['2018–2022 : sciences du vivant.','2022–2024 : bio-informatique et développement.','2023 : première immersion data clinique.','2025–2026 : validation EDC et projets techniques.','2026–2027 : autonomie sur un périmètre junior.','2027–2028 : API, SQL, automatisation pertinente.','2028–2029 : spécialisation logiciels de santé / systèmes informatisés / données cliniques.','2029–2031 : stratégie de test, risques et amélioration continue.'], evidence:'La progression visée repose sur la maîtrise opérationnelle et des preuves de travail.'},
  {id:'future-job', type:'node future', branch:'future', x:2710, y:1510, icon:'26', title:'Prochain chapitre', subtitle:'Premier CDI', kicker:'OBJECTIF IMMÉDIAT', lead:'Rejoindre un environnement structuré et réglementé où contribuer à la validation, la QA, la VSI ou la qualité des données cliniques.', chips:['Validation','QA','VSI','Data clinique'], bullets:['Éditeurs de logiciels de santé.','Sociétés de conseil en validation.','Recherche clinique et industrie pharmaceutique.','Nouvelle-Aquitaine et région parisienne en priorité.'], evidence:'Objectif : devenir autonome sur un périmètre défini, puis élargir progressivement les responsabilités.'}
];
